apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-scc-anyuid
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sql-server-uses-scc-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-anyuid
subjects:
- kind: ServiceAccount
  name: sql-server
