apiVersion: v1
kind: Secret
metadata:
  name: sql-server-seed
stringData:
  # BEWARE! Password complexity rules are enforced by SQL Server!
  sa-password: {{ .Values.saPassword | quote }}
  database-name: {{ .Values.database.name | quote }}
  schema-name: {{ .Values.database.schema | quote }}
  database-username: {{ .Values.database.owner.username | quote }}
  database-password: {{ .Values.database.owner.password | quote }}
